# -*- coding: utf-8 -*-
"""CLASS textprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZE72WiWav3dflmYU_0o5t4Hoat1fKnXa
"""

import os
import re

class TextProcessing:
  def process_text_files(directory_path, process_function):
     for filename in os.listdir(directory_path):
            if filename.endswith(".txt"):
                file_path = os.path.join(directory_path, filename)

                # Read content from the file
                with open(file_path, 'r', encoding='utf-8') as file:
                    content = file.read()

                # Split content into sentences
                sentences = content.split('. ')

                # remove ws and add period to each sentence
                sentences = [sentence.strip() + '.' for sentence in sentences if sentence]

                # Xóa dòng cuối cùng
                if sentences and sentences[-1] == '.':
                    sentences.pop()

                # Ghi nội dung đã tách vào file text gốc
                with open(file_path, 'w', encoding='utf-8') as file:
                    for sentence in sentences:
                        file.write(sentence + '\n')

  def process_remove_last_line(directory_path):
    for filename in os.listdir(directory_path):
            if filename.endswith(".txt"):
                file_path = os.path.join(directory_path, filename)

                # Read content from the file
                with open(file_path, 'r', encoding='utf-8') as file:
                    content_lines = file.readlines()

                # Remove ".\n" from each line
                content_lines = [line.rstrip('.\n') for line in content_lines]

                # Keep all lines except the last one
                content_lines = content_lines[:-1]

                # Ghi nội dung đã chỉnh sửa vào file text gốc
                with open(file_path, 'w', encoding='utf-8') as file:
                    for line in content_lines:
                        file.write(line + '.\n')


  def remove_special_characters(text):
          # Remove special characters: parentheses, hyphens, and slashes
          cleaned_text = re.sub(r'[()\-\\/]', '', text)
          return cleaned_text

      @staticmethod
      def process_with_special_characters(directory_path):
          """
          Process text files in the specified directory by removing special characters.

          Parameters:
          directory_path (str): The directory path containing the text files.
          """
          for filename in os.listdir(directory_path):
              if filename.endswith(".txt"):
                  file_path = os.path.join(directory_path, filename)

                  # Read content from the file
                  with open(file_path, 'r', encoding='utf-8') as file:
                      content = file.read()

                  # Remove special characters
                  cleaned_content = TextProcessing.remove_special_characters(content)

                  # Ghi nội dung đã xử lý vào file text gốc
                  with open(file_path, 'w', encoding='utf-8') as file:
                      file.write(cleaned_content)

directory_path = r'your/folder.path/'

TextProcessing.process_text_files()
TextProcessing.process_remove_last_line(directory_path)
TextProcessing.process_with_special_characters(directory_path)