# -*- coding: utf-8 -*-
"""DPL302m_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o4nKWnIGz4V8I4KCsfb6dti5QxBo_QR3
"""

pip install tensorflow

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

df = pd.read_csv("/content/Housing.csv")

df

scaler = MinMaxScaler()
df[['price', 'area','bedrooms','bathrooms','parking']] = scaler.fit_transform(df[['price','area','bedrooms','bathrooms','parking']])

features = df[["price", "area", "bedrooms", "bathrooms", "parking"]]

target = df["price"]

from sklearn.model_selection import train_test_split

X_train_dev = features[:500]
y_train_dev = features[:500]

X_test = features[-45:]
y_test = features[-45:]

X_train, X_dev, y_train, y_dev = train_test_split(X_train_dev, y_train_dev, test_size=0.2, random_state=42)

from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(units=16, activation='relu', input_dim=5))  # 5 đặc trưng đầu vào
model.add(Dense(units=1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(features, target, epochs=10, batch_size=32)

